AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Create Lambda function to query a database and the API Gateway REST API to
  invoke the function
Parameters:
  ENV:
    Type: String
    Default: development
    AllowedValues:
      - development
      - production
  PPort:
    Description: 'Lambda Environment Variable: PORT'
    Default: 5432
    Type: String
  PS3Bucket:
    Description: Lambda S3Bucket Value
    Default: moxa-api-lambda-postgres
    Type: String
  PSubnetIds:
    Description: Lambda SubnetIds Value
    Default: subnet-d356eedd
    Type: String
  PSecurityGroupIds:
    Description: Lambda SecurityGroupIds Value
    Default: sg-e1a6fac2
    Type: String
  DBInstanceID:
    Default: moxadb
    Description: database instance identifier
    Type: String
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: >-
      Must begin with a letter and must not end with a hyphen or contain two
      consecutive hyphens.
  DBName:
    Default: testdb
    Description: database name
    Type: String
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.
  DBInstanceClass:
    Default: db.t2.micro
    Description: DB instance class
    Type: String
    ConstraintDescription: Must select a valid DB instance type.
  DBAllocatedStorage:
    Default: '20'
    Description: The size of the database (GiB)
    Type: Number
    ConstraintDescription: must be between 20 and 65536 GiB
  DBUsername:
    NoEcho: 'true'
    Description: Username for database access
    Type: String
    Default: TestUser
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    NoEcho: 'true'
    Description: Password database access
    Type: String
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
  GitHubOwner:
    Type: String
    AllowedPattern: '[A-Za-z0-9-]+'
    Default: Faithtosin
  GitToken:
    NoEcho: 'true'
    Description: Password database access
    Type: String
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
  GitHubRepository:
    Type: String
    AllowedPattern: '[A-Za-z0-9-]+'
    Default: Database-Pipeline
  GitHubBranch:
    Type: String
    AllowedPattern: '[A-Za-z0-9-]+'
    Default: main
  CodeBuildEnvironmentImage:
    Type: String
    Default: 'aws/codebuild/standard:4.0'
Mappings:
  LambdaVPCExecutionRole:
    name:
      development: lamda-exrole-dev
      production: lamda-exrole-prod
  ApiGatewayCloudwatchRole:
    name:
      development: ApigatewayCloudwatchRole-dev
      production: ApigatewayCloudwatchRole-prod
Resources:
  RdsDBInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: !Ref DBAllocatedStorage
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      BackupRetentionPeriod: 0
      DBInstanceIdentifier: !Ref DBInstanceID
      DBInstanceClass: !Ref DBInstanceClass
      DBName: !Ref DBName
      Engine: postgres
      EngineVersion: 12.4
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      MultiAZ: false
      Port: 5432
      PubliclyAccessible: true
      StorageType: gp2
      Tags:
        - Key: keyname
          Value: value
  LambdaVPCExecutionRole:
    Description: Assumable role allows Lambda to create ENIs and access VPC
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole'
      RoleName: !FindInMap [LambdaVPCExecutionRole, name, !Ref ENV]

  ServerlessQueryLambdaFunction:
    Description: Create Lambda function using serverless-query.py
    DependsOn: [RdsDBInstance]
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: RDS-Serverless-Query4-dev
      Handler: serverless-query.handler
      Role: !GetAtt LambdaVPCExecutionRole.Arn
      Code:
        S3Bucket: !Ref PS3Bucket
        S3Key: serverless-query.zip
      Runtime: python3.6
      VpcConfig:
        SubnetIds:
          - !Ref PSubnetIds
        SecurityGroupIds:
          - !Ref PSecurityGroupIds
      Environment:
        Variables:
          ENDPOINT: !GetAtt RdsDBInstance.Endpoint.Address
          PORT: !Ref PPort
          DATABASE: !Ref DBName
          DBUSER: !Ref DBUsername
          DBPASSWORD: !Ref DBPassword
  
  ApiGatewayCloudwatchRole:
    Description: Allow API Gateway to publish to CloudWatch logs
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - >-
          arn:aws:iam::aws:policy/service-role/AmazonApiGatewayPushToCloudWatchLogs
      RoleName: apigateway-cloudwatch-role
  ApiGatewayAccount:
    Description: Pass CloudWatch role to API Gateway Account
    Type: 'AWS::ApiGateway::Account'
    Properties:
      CloudWatchRoleArn: !GetAtt ApiGatewayCloudwatchRole.Arn
  ServerlessQueryApi:
    Description: Create API Gateway REST API
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: ServerlessQueryApi
  ServerlessQueryApiResource:
    Description: Create ServerlessQuery4Api Resource
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref ServerlessQueryApi
      ParentId: !GetAtt ServerlessQueryApi.RootResourceId
      PathPart: query
  LambdaInvokePermission:
    Description: Grant ServerlessQueryApi Permission to Invoke ServerlessQuery Lambda function
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt ServerlessQueryLambdaFunction.Arn
      Action: 'lambda:invokeFunction'
      Principal: apigateway.amazonaws.com
      SourceArn: !Join 
        - ''
        - - 'arn:aws:execute-api:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':'
          - !Ref ServerlessQueryApi
          - /*
  
  ServerlessQueryApiMethod:
    Description: Create ServerlessQueryApiResource Method
    DependsOn: LambdaInvokePermission
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Join 
          - ''
          - - 'arn:aws:apigateway:'
            - !Ref 'AWS::Region'
            - ':lambda:path/2015-03-31/functions/'
            - !GetAtt 
              - ServerlessQueryLambdaFunction
              - Arn
            - /invocations
        IntegrationResponses:
          - StatusCode: 200
      ResourceId: !Ref ServerlessQueryApiResource
      RestApiId: !Ref ServerlessQueryApi
      MethodResponses:
        - StatusCode: 200
  
  
  ServerlessQueryApiDeploy:
    Description: Deploy ServerlessQueryApi
    Type: 'AWS::ApiGateway::Deployment'
    DependsOn: [ ServerlessQueryApiMethod ]
    Properties:
      RestApiId: !Ref ServerlessQueryApi
      StageName: test
  DBCodeBuildServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: 1
                Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                  - 'logs:FilterLogEvents'
                  - 'logs:GetLogEvents'
                Resource:
                  - '*'
              - Sid: 2
                Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:GetObjectVersion'
                  - 's3:PutObject'
                  - 's3:GetBucketAcl'
                  - 's3:GetBucketLocation'
                  - 's3:CreateBucket'
                  - 's3:List*'
                  - 's3:PutObject'
                Resource:
                  - '*'
              - Sid: 3
                Effect: Allow
                Action:
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:BatchGetImage'
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:PutImage'
                  - 'ecr:InitiateLayerUpload'
                  - 'ecr:UploadLayerPart'
                  - 'ecr:CompleteLayerUpload'
                  - 'ecr:GetAuthorizationToken'
                  - 'ecr:InitiateLayerUpload'
                  - 'ec2:DescribeNetworkInterfaces'
                  - 'ec2:CreateNetworkInterface'
                  - 'ec2:DescribeDhcpOptions'
                  - 'ec2:DescribeNetworkInterfaces'
                  - 'ec2:DeleteNetworkInterface'
                  - 'ec2:DescribeSubnets'
                  - 'ec2:DescribeSecurityGroups'
                  - 'ec2:DescribeSecurityGroupReferences'
                  - 'ec2:DescribeStaleSecurityGroups'
                  - 'ec2:DescribeVpcs'
                  - 'ec2:CreateNetworkInterfacePermission'
                Resource:
                  - '*'
              - Sid: 4
                Effect: Allow
                Action:
                  - 'iam:AddRoleToInstanceProfile'
                  - 'iam:AttachRolePolicy'
                  - 'iam:CreateInstanceProfile'
                  - 'iam:CreatePolicy'
                  - 'iam:CreateRole'
                  - 'iam:GetRole'
                  - 'iam:ListAttachedRolePolicies'
                  - 'iam:ListPolicies'
                  - 'iam:ListRoles'
                  - 'iam:PassRole'
                  - 'iam:PutRolePolicy'
                  - 'iam:UpdateAssumeRolePolicy'
                Resource:
                  - '*'
              - Sid: 5
                Effect: Allow
                Action:
                  - 'kms:Encrypt'
                  - 'kms:Decrypt'
                  - 'kms:ReEncrypt*'
                  - 'kms:GenerateDataKey*'
                  - 'kms:DescribeKey'
                Resource:
                  - '*'
  DBCodeBuildProjectDeployDev:
    Type: 'AWS::CodeBuild::Project'
    DependsOn:
      - RdsDBInstance
    Properties:
      Name: !Sub '${AWS::StackName}-deploy-dev'
      ServiceRole: !GetAtt DBCodeBuildServiceRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yaml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        PrivilegedMode: true
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !Ref CodeBuildEnvironmentImage
        EnvironmentVariables:
          - Name: ENV_NAME
            Value: dev
          - Name: DBEndPoint
            Value: !GetAtt RdsDBInstance.Endpoint.Address
          - Name: DBname
            Value: !Ref DBName
          - Name: Port
            Value: !Ref PPort
          - Name: DBUser
            Value: !Ref DBUsername
          - Name: Password
            Value: !Ref DBPassword
  DBCodePipelineServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: 6
                Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource:
                  - '*'
              - Sid: 7
                Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:GetObjectVersion'
                  - 's3:PutObject'
                  - 's3:GetBucketAcl'
                  - 's3:GetBucketLocation'
                  - 's3:CreateBucket'
                  - 's3:List*'
                Resource:
                  - '*'
              - Sid: 8
                Action:
                  - 'codebuild:BatchGetBuilds'
                  - 'codebuild:StartBuild'
                  - 'codebuild:BatchGetBuildBatches'
                  - 'codebuild:StartBuildBatch'
                Resource: '*'
                Effect: Allow
              - Sid: 9
                Effect: Allow
                Action:
                  - 'codedeploy:CreateDeployment'
                  - 'codedeploy:GetApplicationRevision'
                  - 'codedeploy:GetDeployment'
                  - 'codedeploy:GetDeploymentConfig'
                  - 'codedeploy:RegisterApplicationRevision'
                Resource:
                  - '*'
              - Sid: 10
                Effect: Allow
                Action:
                  - 'ecs:DescribeServices'
                  - 'ecs:DescribeTaskDefinition'
                  - 'ecs:DescribeTasks'
                  - 'ecs:ListTasks'
                  - 'ecs:RegisterTaskDefinition'
                  - 'ecs:UpdateService'
                Resource:
                  - '*'
  DBCodePipelineArtifactStore:
    Type: 'AWS::S3::Bucket'
    Properties:
      VersioningConfiguration:
        Status: Enabled
  DBCodePipelineWebhook:
    Type: 'AWS::CodePipeline::Webhook'
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Ref GitToken
      RegisterWithThirdParty: 'true'
      Filters:
        - JsonPath: $.ref
          MatchEquals: 'refs/heads/{Branch}'
        - JsonPath: $.repository.name
          MatchEquals: '{Repo}'
      TargetPipeline: !Ref DBCodePipeline
      TargetAction: Source
      TargetPipelineVersion: !GetAtt DBCodePipeline.Version
  DBCodePipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      Name: !Ref 'AWS::StackName'
      RoleArn: !GetAtt DBCodePipelineServiceRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref DBCodePipelineArtifactStore
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepository
                Branch: !Ref GitHubBranch
                PollForSourceChanges: false
                OAuthToken: !Ref GitToken
              OutputArtifacts:
                - Name: SourceCode
        - Name: Dev
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref DBCodeBuildProjectDeployDev
              InputArtifacts:
                - Name: SourceCode
              OutputArtifacts:
                - Name: BuildOutput
Outputs:
  DBHostName:
    Description: database hostname
    Value: !GetAtt 
      - RdsDBInstance
      - Endpoint.Address